package com.example.javaeefirst.mybatis.dao;

import com.example.javaeefirst.mybatis.model.Items;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEMS
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEMS
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    int insert(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEMS
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    Items selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEMS
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    List<Items> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEMS
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    int updateByPrimaryKey(Items record);
}