package com.example.javaeefirst.mybatis.dao;

import com.example.javaeefirst.mybatis.model.ShoppingCart;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ShoppingCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPING_CART
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPING_CART
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    int insert(ShoppingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPING_CART
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    ShoppingCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPING_CART
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    List<ShoppingCart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPING_CART
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    int updateByPrimaryKey(ShoppingCart record);
}