package com.example.javaeefirst.mybatis.dao;

import com.example.javaeefirst.mybatis.model.Shops;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ShopsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPS
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPS
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    int insert(Shops record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPS
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    Shops selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPS
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    List<Shops> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPS
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    int updateByPrimaryKey(Shops record);
}