package com.example.javaeefirst.mybatis.model;

public class Items {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEMS.ID
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEMS.BARCODE
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    private Integer barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEMS.PRICE
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEMS.TITLE
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEMS.ID
     *
     * @return the value of PUBLIC.ITEMS.ID
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEMS.ID
     *
     * @param id the value for PUBLIC.ITEMS.ID
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEMS.BARCODE
     *
     * @return the value of PUBLIC.ITEMS.BARCODE
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    public Integer getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEMS.BARCODE
     *
     * @param barcode the value for PUBLIC.ITEMS.BARCODE
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    public void setBarcode(Integer barcode) {
        this.barcode = barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEMS.PRICE
     *
     * @return the value of PUBLIC.ITEMS.PRICE
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEMS.PRICE
     *
     * @param price the value for PUBLIC.ITEMS.PRICE
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEMS.TITLE
     *
     * @return the value of PUBLIC.ITEMS.TITLE
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEMS.TITLE
     *
     * @param title the value for PUBLIC.ITEMS.TITLE
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }
}