package com.example.javaeefirst.mybatis.model;

import java.util.List;

public class Shops {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOPS.ID
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOPS.ADDRESS
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOPS.TITLE
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    private String title;

    private List<Clients> clients;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOPS.ID
     *
     * @return the value of PUBLIC.SHOPS.ID
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOPS.ID
     *
     * @param id the value for PUBLIC.SHOPS.ID
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOPS.ADDRESS
     *
     * @return the value of PUBLIC.SHOPS.ADDRESS
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOPS.ADDRESS
     *
     * @param address the value for PUBLIC.SHOPS.ADDRESS
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOPS.TITLE
     *
     * @return the value of PUBLIC.SHOPS.TITLE
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOPS.TITLE
     *
     * @param title the value for PUBLIC.SHOPS.TITLE
     *
     * @mbg.generated Tue May 10 18:34:01 EEST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }
}